on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    name: Fetch addon data
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: |
        ./curse.sh curse.json
        ./tukui.sh tukui.json
        ./wowi.sh wowi.json
        ./townlong_yak.sh townlong_yak.json
        # old catalog, maintained to keep older version of Ajour functional
        jq -c -s '.[0] + .[1] + .[2] + .[3]' tukui.json curse.json wowi.json > catalog.json
        # New catalog
        jq -c -s '.[0] + .[1] + .[2] + .[3]' tukui.json curse.json wowi.json townlong_yak.json > catalog-2.1.json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add catalog.json catalog-2.0.json curse.json tukui.json wowi.json townlong_yak.json
        git commit -m "chore: updated catalog"
        git push
